name: Push component to https://components.espressif.com
on:
  push:
jobs:
  upload_components:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: "recursive"

      - name: Upload component to the component registry
        uses: espressif/upload-components-ci-action@dont-fail-immediately
        with:
          directories: "comp_a;comp_b;comp_c"
          namespace: "kumekay"
          api_token: ${{ secrets.IDF_COMPONENT_API_TOKEN }}
